# Payment Status 
PAYMENT_PENDING = 1
PAYMENT_COMPLETED = 2
PAYMENT_FAILED = 3

# Order Item status
ORDER_ITEM_PROCESSING = 1
ORDER_ITEM_SHIPPED = 2
ORDER_ITEM_DELIVERED = 3
ORDER_ITEM_CANCELLED = 4

# Error messages
CART_EMPTY_ERROR_MESSAGE = "Cart is empty. Please add a product to the order."