# Generated by Django 4.2.3 on 2023-07-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_selleraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('store_link', models.SlugField(unique=True)),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.selleraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
