# Generated by Django 4.2.3 on 2023-07-15 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customeraccount'),
        ('orders', '0002_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.TextField()),
                ('payment_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (3, 'Failed')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customeraccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
